defaults: &defaults

  debug: True

  databases:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: poolapp_django
      USER: poolapp
      PASSWORD: standyco # Move this into separete yaml file
      HOST: localhost
      PORT: 5432

development:
  <<: *defaults
  
staging:
  <<: *defaults

production:
  <<: *defaults

  debug: True

  databases:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: dafjuu4ppl1upt
      USER: lfzbxbwvytkqpz
      PASSWORD: 3Z03NQiyvJBbgJrfoVMuuhRKLz # Move this into separete yaml file
      HOST: ec2-107-20-159-103.compute-1.amazonaws.com
      PORT: 5432
