defaults: &defaults

  debug: False

  postgres:
    db_name: poolapp_django
    user: poolapp
    password: standyco
    host: localhost
    port: 5432

development:
  <<: *defaults
  
  debug: True
    

staging:
  <<: *defaults

  debug: True

production:
  <<: *defaults
